import { doctorAgent } from "@/app/(routes)/dashboard/_components/DoctorAgentCard";
export const AIDoctorAgents: doctorAgent[] = [
  {
    id: 1,
    specialist: "General Physician",
    description: "Handles fever, cold, flu, infections, and general health checkups.",
    image: "/doctor1.png",
    agentPrompt: "You are a highly experienced general physician. Assist patients with common illnesses and guide them with initial treatments.",
    keywords: ["fever", "cold", "cough", "infection", "headache", "body pain", "general"],
    voiceId: "Elliot",
  },
  {
    id: 2,
    specialist: "Cardiologist",
    description: "Expert in treating heart-related conditions such as chest pain and hypertension.",
    image: "/doctor2.png",
    agentPrompt: "You are an expert cardiologist. Help patients with heart problems, blood pressure, and related symptoms.",
    keywords: ["chest pain", "heart", "hypertension", "bp", "fatigue", "breathless"],
    voiceId: "Hook",
  },
  {
    id: 3,
    specialist: "Dermatologist",
    description: "Specializes in skin conditions like acne, rashes, and allergies.",
    image: "/doctor3.png",
    agentPrompt: "You are a skilled dermatologist. Guide users with skin issues like acne, allergies, and infections.",
    keywords: ["skin", "rash", "itching", "acne", "eczema", "allergy"],
    voiceId: "Hook",
  },
  {
    id: 4,
    specialist: "Psychiatrist",
    description: "Helps with mental health issues like anxiety, stress, and depression.",
    image: "/doctor4.png",
    agentPrompt: "You are a compassionate psychiatrist. Support patients facing mental health challenges.",
    keywords: ["depression", "anxiety", "mental", "stress", "sleep", "insomnia"],
    voiceId: "Navya",
  },
  {
    id: 5,
    specialist: "Pediatrician",
    description: "Treats children and infants with care for childhood diseases.",
    image: "/doctor5.png",
    agentPrompt: "You are a friendly pediatrician. Help parents understand and treat their children’s symptoms.",
    keywords: ["child", "baby", "pediatric", "fever", "vomiting", "diarrhea"],
    voiceId: "Ayla",
  },
  {
    id: 6,
    specialist: "Orthopedic Surgeon",
    description: "Expert in bone, joint, and muscle-related problems.",
    image: "/doctor6.png",
    agentPrompt: "You are a professional orthopedic doctor. Help with fractures, back pain, and joint injuries.",
    keywords: ["bone", "joint", "fracture", "back pain", "arthritis", "knee"],
    voiceId: "Eileen",
  },
  {
    id: 7,
    specialist: "ENT Specialist",
    description: "Treats issues related to ears, nose, and throat.",
    image: "/doctor7.png",
    agentPrompt: "You are an ENT specialist. Guide users with sinus, ear infections, and throat problems.",
    keywords: ["ear", "nose", "throat", "sinus", "infection", "hearing"],
    voiceId: "Melissa",
  },
  {
    id: 8,
    specialist: "Gynecologist",
    description: "Focuses on women's health, menstruation, and reproductive issues.",
    image: "/doctor8.png",
    agentPrompt: "You are a gynecologist. Help with periods, pregnancy symptoms, and female reproductive health.",
    keywords: ["period", "pregnancy", "menstruation", "cramps", "fertility"],
    voiceId: "Pia",
  },
  {
    id: 9,
    specialist: "Neurologist",
    description: "Specialist in brain, spine, and nerve disorders.",
    image: "/doctor9.png",
    agentPrompt: "You are a neurologist. Help patients with migraines, seizures, and neural issues.",
    keywords: ["headache", "migraine", "seizure", "nerve", "spine", "neuropathy"],
    voiceId: "Chris",
  },
  {
    id: 10,
    specialist: "Gastroenterologist",
    description: "Treats digestive system issues like acidity and stomach pain.",
    image: "/doctor10.png",
    agentPrompt: "You are a gastroenterologist. Help with digestion, bloating, acidity, and liver-related conditions.",
    keywords: ["stomach", "digestion", "acidity", "liver", "bloating", "nausea"],
    voiceId: "Nolan",
  },
];
